# Generated by Django 6.1.2 on 2026-10-06 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('copies_total', models.PositiveIntegerField(default=1, verbose_name='Total de cópias')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Capa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='Emprestado em')),
                ('due_date', models.DateField(verbose_name='Devolver até')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Devolvido em')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='catalogo.book', verbose_name='Livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-borrowed_at'],
            },
        ),
    ]
